// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbeqnqFtLWzbKuuDgnU9NXy73lFbxDa3s',
    appId: '1:1046037338105:web:d0630971fd17791bba4f28',
    messagingSenderId: '1046037338105',
    projectId: 'gradease-a5c4e',
    authDomain: 'gradease-a5c4e.firebaseapp.com',
    storageBucket: 'gradease-a5c4e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgGCA6Tlx_vtsGNNsl98Mm02O1lntBxHE',
    appId: '1:1046037338105:android:695d1d4813ff137aba4f28',
    messagingSenderId: '1046037338105',
    projectId: 'gradease-a5c4e',
    storageBucket: 'gradease-a5c4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKJuHu_tI_OqkJR4u8gPZGUGHHRV4AAxM',
    appId: '1:1046037338105:ios:5879efa15a430130ba4f28',
    messagingSenderId: '1046037338105',
    projectId: 'gradease-a5c4e',
    storageBucket: 'gradease-a5c4e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKJuHu_tI_OqkJR4u8gPZGUGHHRV4AAxM',
    appId: '1:1046037338105:ios:5879efa15a430130ba4f28',
    messagingSenderId: '1046037338105',
    projectId: 'gradease-a5c4e',
    storageBucket: 'gradease-a5c4e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbeqnqFtLWzbKuuDgnU9NXy73lFbxDa3s',
    appId: '1:1046037338105:web:6a137f70a95a57b5ba4f28',
    messagingSenderId: '1046037338105',
    projectId: 'gradease-a5c4e',
    authDomain: 'gradease-a5c4e.firebaseapp.com',
    storageBucket: 'gradease-a5c4e.firebasestorage.app',
  );
}
